feat: first-implement
eggjs/egg-watcher-chokidar pull request #1
Opened 2017-02-16 11:51 UTC by alphatr

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

first implement add egg-watcher with vagrant support

Pleace config travis-ci

2017-02-16 11:51 UTC, alphatr commented
@atian25

2017-02-16 12:45 UTC, atian25 requested changes
辛苦了

2017-02-16 12:45 UTC, atian25 commented on .autod.conf.js
> +    'egg-watcher',
watcher 是内置的，不用引入

2017-02-16 12:45 UTC, atian25 commented on .editorconfig
> +
干掉这文件

2017-02-16 12:45 UTC, atian25 commented on History.md
> +==================
这个干掉，发布时通过指令自动生成的

2017-02-16 12:45 UTC, atian25 commented on README.md
> +File watcher plugin for egg watcher when in network file systems or other virtualization software
说明加到 badge 下面，原来有注释那里

2017-02-16 12:45 UTC, atian25 commented on README.md
> +exports['watcher-vagrant'] = {
驼峰

2017-02-16 12:45 UTC, atian25 commented on README.md
> +  vagrant: {
不用额外节点了

2017-02-16 12:45 UTC, atian25 commented on config/config.default.js
> + * @file default vagrant watcher config
顶部不用这个

2017-02-16 12:45 UTC, atian25 commented on config/config.default.js
> + * @property {string} type - event source type
String

2017-02-16 12:45 UTC, atian25 commented on config/config.local.js
> +  type: 'vagrant',
这几个怎么不放在 default 那边？有什么特殊的考虑么？

2017-02-16 12:45 UTC, atian25 commented on config/config.unittest.js
> +exports.watcher = {
unittest 会继承 default，不需要这文件了

2017-02-16 12:45 UTC, atian25 commented on lib/vagrant.js
> +    this._handler.unwatch(path);
如果没有任何 handler 需要设置为 undefined 么？

2017-02-16 12:45 UTC, atian25 commented on package.json
> +    "name": "watcher-vagrant",
驼峰

2017-02-16 12:45 UTC, atian25 commented on package.json
> +    "egg-watcher": "^2.0.0",
内置的，不需要引入

2017-02-16 12:45 UTC, atian25 commented on package.json
>    "author": "TZ <atian25@qq.com>",
改为你吧

2017-02-16 13:02 UTC, popomore commented on config/config.local.js
> +  type: 'vagrant',
因为这个只在 local 开启？

2017-02-16 13:55 UTC, alphatr commented on config/config.local.js
> +  type: 'vagrant',
是的，这个和 egg-watcher 类似，只默认在 local 和 unittest 环境开启

2017-02-16 13:55 UTC, alphatr commented on config/config.local.js
> +  type: 'vagrant',
是的，这个和 egg-watcher 类似，只默认在 local 和 unittest 环境开启

2017-02-16 14:03 UTC, alphatr commented on config/config.unittest.js
> +exports.watcher = {
同上，default 默认不开启，而 unittest 开启

2017-02-16 14:14 UTC, shaoshuai0102 reviewed
1. chokidar 能覆盖你说的所有的情况么？如果可以的话要改个名字，vegerant不合适了
2. 用例测试的还是普通的文件系统吧？好像比较难模拟真实运行情况

2017-02-16 14:14 UTC, shaoshuai0102 commented on .gitignore
> +._*
加一个  .vscode

2017-02-16 14:14 UTC, shaoshuai0102 commented on History.md
> +==================
整个文件情况或者删掉吧发布会加

2017-02-16 14:14 UTC, shaoshuai0102 commented on README.md
> +exports['watcher-vagrant'] = {
watcherVagrant

2017-02-16 14:14 UTC, shaoshuai0102 commented on README.md
> +  vagrant: {
exports.watcherVagrant = {}

2017-02-16 14:14 UTC, shaoshuai0102 commented on config/config.local.js
> +    alwaysStat: true,
这个配置放 default 把。exports.watcherVagrant

2017-02-16 14:14 UTC, shaoshuai0102 commented on test/vagrant.test.js
> +      plugin: 'watcher',
Plugin 字段都不用传，而且你也传错了，删掉吧

2017-02-17 01:32 UTC, atian25 commented
@shaoshuai0102 当时写 wt 是因为 chokidar 太复杂了么?

2017-02-17 01:33 UTC, atian25 commented on config/config.local.js
> +    alwaysStat: true,
这种二级插件, 配置是 watcherVagrant 还是 watcher.agrant 好呢? 这块感觉要讨论下.

cc @popomore

2017-02-17 01:33 UTC, popomore commented
fsvent 的关系？
TZ | 天猪 <notifications@github.com>于2017年2月17日 周五09:32写道：

> @shaoshuai0102 <https://github.com/shaoshuai0102> 当时写 wt 是因为 chokidar
> 太复杂了么?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/eggjs/egg-watcher-vagrant/pull/1#issuecomment-280522352>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAWA1TatuDBfd7hHGeFo6wKhtKedddYoks5rdPjGgaJpZM4MC6tJ>
> .
>

2017-02-17 01:34 UTC, popomore commented on config/config.local.js
> +    alwaysStat: true,
驼峰吧，属性不能用 .

2017-02-17 01:35 UTC, atian25 commented on config/config.local.js
> +  type: 'vagrant',
`usePolling: true, alwaysStat: true,` 这些配置项可以放在 default 里面.
只是在 local 和 unittest 配置 type 来开启就好了.

2017-02-17 01:36 UTC, shaoshuai0102 commented
对 mac 下腰编译 fsevent，比较麻烦。

@fengmk2 要不我们之前用 chokidar 吧，开源社区对它的使用还是蛮广泛的

2017-02-17 01:37 UTC, shaoshuai0102 commented on config/config.local.js
> +    alwaysStat: true,
虽然这是二级插件，实际上是没有这个概念的，这个是虚拟的。所以按照一般的插件规范来做就好了

2017-02-17 01:47 UTC, atian25 commented on config/config.local.js
> +    alwaysStat: true,
@popomore 就是现在他的做法，. 是 config.watcher.vagrant 而不是，config['watcher.vagrant']

2017-02-17 01:56 UTC, popomore commented on config/config.local.js
> +    alwaysStat: true,
就是插件配置和插件名统一比较好，不过这也不是强约定，我们看到的就统一一下好了

2017-02-17 02:12 UTC, shaoshuai0102 commented on config/config.local.js
> +    alwaysStat: true,
config.watcherVagrant 这样~

2017-02-17 02:17 UTC, alphatr commented
@shaoshuai0102  chokidar 是可以覆盖其他情况的，我自己本地没有做过测试；确实是测试不太好覆盖

2017-02-17 02:19 UTC, shaoshuai0102 commented
改名叫 egg-watcher-chokidar 吧。你先改代码里的字段，后面我们来 move 仓库

2017-02-17 02:21 UTC, shaoshuai0102 commented
https://www.npmjs.com/package/egg-watcher-vagrant 你都给发布了。。  pr 没合的时候不要发布模块。等合并后再发布哈 @alphatr

2017-02-17 02:25 UTC, atian25 commented
我今天写下发布和协作流程吧.

2017-02-17 02:26 UTC, atian25 commented on config/config.local.js
> +    alwaysStat: true,
我发现有点更喜欢:
`config.watcher.vargrant`, `config.passport.github`, `config.view.ejs`

2017-02-17 02:34 UTC, shaoshuai0102 commented on config/config.local.js
> +    alwaysStat: true,
这个和插件本身的命名约定冲突了，感觉必要性不大，没必要再做新的。

2017-02-17 02:54 UTC, popomore commented
member guide 还是需要的

2017-02-17 02:55 UTC, popomore commented
@alphatr 给你加 admin 了

2017-02-17 03:15 UTC, alphatr commented
@popomore 好，谢谢！

2017-02-17 03:16 UTC, popomore commented
@alphatr 可以看看 https://github.com/eggjs/egg/blob/master/CONTRIBUTING.zh-CN.md，如果有什么没写的，可以提醒我们补充。

2017-02-17 03:48 UTC, atian25 commented on config/config.local.js
> +    alwaysStat: true,
嗯嗯, @alphatr 先按 config.watcherVagrant 的方式吧

2017-02-17 03:49 UTC, atian25 commented on config/config.local.js
> +    alwaysStat: true,
喔, 是 watcherChokidar ?

2017-02-17 05:09 UTC, alphatr commented
@popomore @shaoshuai0102 之前没看到这篇文档，发布到 npm 了，既然看到了文档，后面就会按照文档来。

2017-02-17 05:45 UTC, atian25 reviewed
其他 +1

2017-02-17 05:45 UTC, atian25 commented on README.zh_CN.md
> -# egg-watcher-vagrant
中文文档也补上吧

2017-02-17 05:45 UTC, atian25 commented on config/config.default.js
> +  chokidar: {
这里没改, 要改为 `exports.watcherChokidar`

2017-02-17 05:45 UTC, atian25 commented on lib/chokidar.js
> +        .on('error', err => debug(`watcher error: ${err}`))
debug 是要开环境变量才能看到的, 这个信息关键么? 如果关键的话就要用 logger,  @shaoshuai0102 这里能拿到 ref 么?

2017-02-17 05:45 UTC, atian25 commented on package.json
> +    "egg": "^0.11.0",
跑下 `npm run autod`

2017-02-17 06:31 UTC, alphatr commented on config/config.default.js
> +  chokidar: {
@atian25 watcher 里面调用 `EventSource` 传入的 options 只是这里的 `exports.watcher`，如果 `exports.watcherChokidar` 这样，我 `ChokidarEventSource` 就拿不到了

2017-02-17 06:43 UTC, shaoshuai0102 commented on lib/chokidar.js
> +        .on('error', err => debug(`watcher error: ${err}`))
用 logger 打印  error 不能吞掉

2017-02-17 06:43 UTC, shaoshuai0102 commented on config/config.default.js
> +  chokidar: {
这里我想一下，watcher 可能得改造下，之前没注意这个细节

2017-02-17 06:44 UTC, alphatr commented on lib/chokidar.js
> +        .on('error', err => debug(`watcher error: ${err}`))
这里我觉得改为错误抛给 watcher 可能更合适

2017-02-17 06:47 UTC, shaoshuai0102 commented on lib/chokidar.js
> +        .on('error', err => debug(`watcher error: ${err}`))
你说的对  watcher 会借住  你直接 emit 出去就好了

2017-02-17 06:48 UTC, atian25 commented on config/config.default.js
> +  chokidar: {
如果  ChokidarEventSource 里面能拿到 app, 就不怕, 要看看怎么改造, 参考下 view 的提案?

2017-02-17 06:48 UTC, shaoshuai0102 commented on lib/chokidar.js
> +        .on('error', err => debug(`watcher error: ${err}`))
- https://github.com/eggjs/egg-watcher/blob/master/lib/event-sources/development.js#L18
- https://github.com/eggjs/egg-watcher/blob/master/lib/watcher.js#L18
- https://github.com/eggjs/egg-watcher/blob/master/agent.js#L13

2017-02-17 06:53 UTC, atian25 commented on config/config.default.js
> +  chokidar: {
@shaoshuai0102 类似 https://github.com/eggjs/egg/issues/398

2017-02-17 08:29 UTC, shaoshuai0102 commented on config/config.default.js
> +  chokidar: {
https://github.com/eggjs/egg-watcher/pull/4

2017-02-17 10:35 UTC, atian25 submitted a review, later dismissed

2017-02-17 10:35 UTC, atian25 commented on test/chokidar.test.js
> +    app.ready(done);
return app.ready()

2017-02-17 10:35 UTC, atian25 commented on test/fixtures/apps/watcher-chokidar-app/config/config.unittest.js
> +exports.env = 'local';
这是干嘛的？

2017-02-17 10:35 UTC, atian25 commented on test/fixtures/apps/watcher-chokidar-app/config/plugin.js
> +module.exports = {
不需要这个文件，会自动加载你这个插件的

2017-02-17 10:35 UTC, atian25 commented on test/utils.js
> +  return path.join(fixtures, name);
也不需要这个，默认是那个目录，写相对路径即可

2017-02-17 10:36 UTC, atian25 commented on test/utils.js
> +  return path.join(fixtures, name);
这里我理解错了，没问题

2017-02-17 10:38 UTC, shaoshuai0102 commented
@alphatr 第一个插件 cr 起来都有点麻烦，别着急哈。后面就 easy 了

2017-02-17 10:42 UTC, atian25 commented
哈哈，想起我那时候第一个 pr 

发自我的 iPhone

> 在 2017年2月17日，18:38，Shawn <notifications@github.com> 写道：
> 
> @alphatr 第一个插件 cr 起来都有点麻烦，别着急哈。后面就 easy 了
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-02-18 11:55 UTC, popomore commented on README.zh_CN.md
> -# egg-watcher-vagrant
我不建议在插件写中文，两份维护好麻烦

2017-02-19 01:44 UTC, shaoshuai0102 commented on README.zh_CN.md
> -# egg-watcher-vagrant
是的，只写英文吧

2017-02-19 04:35 UTC, atian25 commented on README.zh_CN.md
> -# egg-watcher-vagrant
OK

2017-02-20 02:05 UTC, alphatr commented on README.zh_CN.md
> -# egg-watcher-vagrant
好吧，我把中文文档去掉了

2017-02-20 06:19 UTC, shaoshuai0102 approved these changes
LGTM

2017-02-20 06:23 UTC, merged

2017-02-20 06:24 UTC, shaoshuai0102 commented
@popomore 怎么发布模块的 guide 有了么 `git release`那一套

2017-02-20 06:25 UTC, popomore commented
好像没有，就是原来 @fengmk2 写的那个

2017-02-20 06:25 UTC, shaoshuai0102 commented
@popomore 顺便帮忙加个 repo 的 admin 权限，我rename 一下 repo

2017-02-20 06:28 UTC, popomore commented
给你加 group owner 了

2017-02-20 06:31 UTC, shaoshuai0102 commented
`egg-watcher-chokidar@1.0.0`

2017-02-20 06:33 UTC, shaoshuai0102 commented
```bash
-> npm owner ls
alphatr <alphatr@alphatr.com>
atian25 <atian25@qq.com>
popomore <sakura9515@gmail.com>
shaoshuai0102 <shaoshuai0102@gmail.com>
```

2017-02-20 08:29 UTC, alphatr commented
@shaoshuai0102 还有个问题，就是 egg-watcher 2.1.0 还没发到 npm，这个包的配置暂时还不能生效

2017-02-20 08:47 UTC, atian25 commented
稍等, 我看看

2017-02-20 08:50 UTC, atian25 commented
发了